services:
  cube:
    image: cubejs/cube:latest
    user: "1000:1000"   # 改成你的 uid:gid
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
    volumes:
      - .:/cube/conf
