all:
	sudo docker-compose up -d

stop:
	sudo docker-compose stop

down:
	sudo docker-compose down

pull:
	docker pull cubejs/cube:latest
	# sudo docker pull cubejs/cube:latest
	# sudo docker pull --registry-mirror=https://486bwdh1.mirror.aliyuncs.com cubejs/cube:latest

